CALL add_medical_history(1, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(2, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(3, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(4, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(5, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(6, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(7, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(8, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(9, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(10, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(11, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(12, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(13, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(14, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(15, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(16, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(17, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(18, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(19, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(20, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(21, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(22, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(23, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(24, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(25, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(26, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(27, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(28, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(29, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(30, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(31, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(32, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(33, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(34, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(35, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(36, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(37, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(38, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(39, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(40, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(41, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(42, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(43, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(44, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(45, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(46, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(47, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(48, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(49, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(50, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(51, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(52, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(53, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(54, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(55, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(56, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(57, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(58, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(59, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(60, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(61, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(62, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(63, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(64, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(65, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(66, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(67, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(68, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(69, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(70, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(71, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(72, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(73, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(74, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(75, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(76, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(77, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(78, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(79, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(80, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(81, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(82, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(83, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(84, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(85, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(86, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(87, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(88, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(89, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(90, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(91, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(92, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(93, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(94, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(95, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(96, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(97, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(98, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(99, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(100, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(101, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(102, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(103, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(104, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(105, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(106, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(107, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(108, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(109, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(110, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(111, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(112, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(113, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(114, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(115, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(116, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(117, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(118, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(119, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(120, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(121, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(122, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(123, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(124, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(125, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(126, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(127, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(128, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(129, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(130, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(131, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(132, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(133, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(134, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(135, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(136, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(137, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(138, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(139, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(140, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(141, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(142, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(143, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(144, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(145, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(146, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(147, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(148, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(149, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(150, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(151, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(152, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(153, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(154, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(155, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(156, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(157, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(158, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(159, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(160, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(161, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(162, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(163, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(164, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(165, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(166, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(167, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(168, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(169, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(170, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(171, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(172, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(173, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(174, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(175, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(176, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(177, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(178, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(179, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(180, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(181, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(182, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(183, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(184, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(185, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(186, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(187, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(188, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(189, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(190, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(191, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(192, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(193, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(194, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(195, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(196, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(197, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(198, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(199, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(200, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(201, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(202, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(203, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(204, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(205, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(206, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(207, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(208, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(209, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(210, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(211, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(212, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(213, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(214, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(215, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(216, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(217, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(218, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(219, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(220, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(221, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(222, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(223, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(224, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(225, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(226, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(227, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(228, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(229, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(230, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(231, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(232, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(233, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(234, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(235, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(236, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(237, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(238, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(239, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(240, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(241, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(242, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(243, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(244, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(245, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(246, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(247, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(248, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(249, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(250, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(251, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(252, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(253, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(254, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(255, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(256, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(257, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(258, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(259, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(260, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(261, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(262, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(263, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(264, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(265, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(266, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(267, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(268, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(269, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(270, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(271, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(272, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(273, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(274, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(275, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(276, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(277, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(278, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(279, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(280, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(281, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(282, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(283, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(284, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(285, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(286, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(287, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(288, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(289, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(290, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(291, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(292, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(293, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(294, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(295, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(296, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(297, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(298, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(299, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(300, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(301, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(302, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(303, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(304, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(305, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(306, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(307, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(308, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(309, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(310, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(311, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(312, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(313, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(314, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(315, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(316, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(317, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(318, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(319, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(320, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(321, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(322, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(323, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(324, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(325, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(326, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(327, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(328, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(329, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(330, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(331, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(332, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(333, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(334, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(335, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(336, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(337, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(338, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(339, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(340, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(341, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(342, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(343, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(344, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(345, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(346, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(347, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(348, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(349, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(350, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(351, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(352, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(353, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(354, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(355, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(356, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(357, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(358, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(359, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(360, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(361, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(362, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(363, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(364, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(365, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(366, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(367, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(368, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(369, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(370, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(371, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(372, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(373, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(374, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(375, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(376, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(377, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(378, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(379, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(380, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(381, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(382, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(383, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(384, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(385, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(386, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(387, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(388, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(389, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(390, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(391, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(392, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(393, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(394, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(395, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(396, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(397, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(398, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(399, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(400, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(401, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(402, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(403, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(404, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(405, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(406, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(407, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(408, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(409, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(410, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(411, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(412, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(413, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(414, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(415, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(416, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(417, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(418, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(419, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(420, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(421, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(422, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(423, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(424, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(425, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(426, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(427, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(428, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(429, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(430, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(431, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(432, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(433, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(434, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(435, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(436, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(437, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(438, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(439, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(440, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(441, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(442, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(443, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(444, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(445, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(446, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(447, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(448, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(449, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(450, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(451, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(452, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(453, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(454, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(455, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(456, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(457, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(458, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(459, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(460, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(461, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(462, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(463, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(464, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(465, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(466, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(467, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(468, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(469, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(470, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(471, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(472, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(473, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(474, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(475, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(476, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(477, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(478, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(479, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(480, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(481, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(482, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(483, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(484, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(485, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(486, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(487, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(488, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(489, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(490, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(491, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(492, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(493, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(494, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(495, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(496, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(497, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(498, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(499, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(500, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(501, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(502, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(503, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(504, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(505, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(506, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(507, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(508, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(509, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(510, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(511, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(512, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(513, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(514, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(515, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(516, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(517, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(518, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(519, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(520, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(521, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(522, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(523, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(524, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(525, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(526, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(527, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(528, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(529, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(530, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(531, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(532, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(533, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(534, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(535, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(536, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(537, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(538, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(539, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(540, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(541, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(542, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(543, '3 doses, Fully vaccinated', NULL);
CALL add_medical_history(544, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(545, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(546, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(547, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(548, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(549, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(550, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(551, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(552, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(553, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(554, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(555, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(556, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(557, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(558, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(559, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(560, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(561, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(562, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(563, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(564, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(565, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(566, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(567, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(568, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(569, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(570, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(571, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(572, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(573, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(574, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(575, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(576, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(577, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(578, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(579, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(580, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(581, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(582, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(583, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(584, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(585, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(586, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(587, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(588, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(589, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(590, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(591, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(592, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(593, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(594, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(595, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(596, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(597, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(598, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(599, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(600, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(601, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(602, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(603, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(604, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(605, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(606, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(607, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(608, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(609, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(610, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(611, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(612, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(613, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(614, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(615, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(616, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(617, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(618, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(619, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(620, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(621, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(622, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(623, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(624, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(625, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(626, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(627, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(628, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(629, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(630, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(631, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(632, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(633, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(634, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(635, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(636, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(637, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(638, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(639, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(640, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(641, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(642, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(643, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(644, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(645, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(646, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(647, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(648, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(649, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(650, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(651, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(652, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(653, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(654, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(655, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(656, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(657, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(658, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(659, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(660, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(661, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(662, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(663, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(664, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(665, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(666, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(667, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(668, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(669, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(670, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(671, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(672, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(673, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(674, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(675, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(676, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(677, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(678, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(679, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(680, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(681, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(682, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(683, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(684, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(685, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(686, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(687, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(688, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(689, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(690, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(691, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(692, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(693, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(694, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(695, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(696, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(697, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(698, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(699, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(700, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(701, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(702, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(703, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(704, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(705, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(706, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(707, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(708, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(709, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(710, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(711, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(712, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(713, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(714, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(715, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(716, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(717, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(718, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(719, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(720, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(721, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(722, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(723, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(724, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(725, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(726, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(727, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(728, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(729, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(730, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(731, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(732, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(733, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(734, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(735, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(736, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(737, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(738, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(739, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(740, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(741, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(742, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(743, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(744, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(745, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(746, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(747, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(748, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(749, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(750, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(751, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(752, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(753, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(754, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(755, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(756, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(757, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(758, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(759, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(760, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(761, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(762, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(763, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(764, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(765, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(766, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(767, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(768, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(769, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(770, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(771, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(772, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(773, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(774, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(775, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(776, '3 doses, Fully vaccinated', 'negative');
CALL add_medical_history(777, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(778, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(779, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(780, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(781, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(782, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(783, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(784, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(785, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(786, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(787, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(788, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(789, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(790, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(791, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(792, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(793, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(794, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(795, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(796, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(797, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(798, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(799, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(800, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(801, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(802, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(803, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(804, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(805, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(806, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(807, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(808, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(809, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(810, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(811, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(812, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(813, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(814, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(815, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(816, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(817, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(818, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(819, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(820, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(821, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(822, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(823, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(824, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(825, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(826, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(827, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(828, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(829, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(830, '3 doses, Fully vaccinated', 'positive');
CALL add_medical_history(831, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(832, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(833, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(834, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(835, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(836, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(837, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(838, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(839, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(840, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(841, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(842, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(843, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(844, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(845, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(846, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(847, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(848, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(849, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(850, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(851, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(852, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(853, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(854, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(855, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(856, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(857, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(858, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(859, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(860, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(861, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(862, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(863, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(864, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(865, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(866, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(867, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(868, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(869, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(870, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(871, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(872, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(873, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(874, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(875, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(876, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(877, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(878, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(879, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(880, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(881, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(882, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(883, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(884, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(885, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(886, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(887, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(888, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(889, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(890, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(891, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(892, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(893, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(894, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(895, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(896, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(897, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(898, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(899, '2 doses, Pfizer-BioNTech', NULL);
CALL add_medical_history(900, '2 doses, Sinovac', NULL);
CALL add_medical_history(901, '2 doses, Sinovac', NULL);
CALL add_medical_history(902, '2 doses, Sinovac', NULL);
CALL add_medical_history(903, '2 doses, Sinovac', NULL);
CALL add_medical_history(904, '2 doses, Sinovac', NULL);
CALL add_medical_history(905, '2 doses, Sinovac', NULL);
CALL add_medical_history(906, '2 doses, Sinovac', NULL);
CALL add_medical_history(907, '2 doses, Sinovac', NULL);
CALL add_medical_history(908, '2 doses, Sinovac', NULL);
CALL add_medical_history(909, '2 doses, Sinovac', NULL);
CALL add_medical_history(910, '2 doses, Sinovac', NULL);
CALL add_medical_history(911, '2 doses, Sinovac', NULL);
CALL add_medical_history(912, '2 doses, Sinovac', NULL);
CALL add_medical_history(913, '2 doses, Sinovac', NULL);
CALL add_medical_history(914, '2 doses, Sinovac', NULL);
CALL add_medical_history(915, '2 doses, Sinovac', NULL);
CALL add_medical_history(916, '2 doses, Sinovac', NULL);
CALL add_medical_history(917, '2 doses, Sinovac', NULL);
CALL add_medical_history(918, '2 doses, Sinovac', NULL);
CALL add_medical_history(919, '2 doses, Sinovac', NULL);
CALL add_medical_history(920, '2 doses, Sinovac', NULL);
CALL add_medical_history(921, '2 doses, Sinovac', NULL);
CALL add_medical_history(922, '2 doses, Sinovac', NULL);
CALL add_medical_history(923, '2 doses, Sinovac', NULL);
CALL add_medical_history(924, '2 doses, Sinovac', NULL);
CALL add_medical_history(925, '2 doses, Sinovac', NULL);
CALL add_medical_history(926, '2 doses, Sinovac', NULL);
CALL add_medical_history(927, '2 doses, Sinovac', NULL);
CALL add_medical_history(928, '2 doses, Sinovac', NULL);
CALL add_medical_history(929, '2 doses, Sinovac', NULL);
CALL add_medical_history(930, '2 doses, Sinovac', NULL);
CALL add_medical_history(931, '2 doses, Sinovac', NULL);
CALL add_medical_history(932, '2 doses, Sinovac', NULL);
CALL add_medical_history(933, '2 doses, Sinovac', NULL);
CALL add_medical_history(934, '2 doses, Sinovac', NULL);
CALL add_medical_history(935, '2 doses, Sinovac', NULL);
CALL add_medical_history(936, '2 doses, Sinovac', NULL);
CALL add_medical_history(937, '2 doses, Sinovac', NULL);
CALL add_medical_history(938, '2 doses, Sinovac', NULL);
CALL add_medical_history(939, '2 doses, Sinovac', NULL);
CALL add_medical_history(940, '2 doses, Sinovac', NULL);
CALL add_medical_history(941, '2 doses, Sinovac', NULL);
CALL add_medical_history(942, '2 doses, Sinovac', NULL);
CALL add_medical_history(943, '2 doses, Sinovac', NULL);
CALL add_medical_history(944, '2 doses, Sinovac', NULL);
CALL add_medical_history(945, NULL, 'positive');
CALL add_medical_history(946, NULL, 'positive');
CALL add_medical_history(947, NULL, 'positive');
CALL add_medical_history(948, NULL, 'positive');
CALL add_medical_history(949, NULL, 'positive');
CALL add_medical_history(950, NULL, 'positive');
CALL add_medical_history(951, NULL, 'positive');
CALL add_medical_history(952, NULL, 'positive');
CALL add_medical_history(953, NULL, 'positive');
CALL add_medical_history(954, NULL, 'positive');
CALL add_medical_history(955, NULL, 'positive');
CALL add_medical_history(956, NULL, 'positive');
CALL add_medical_history(957, NULL, 'positive');
CALL add_medical_history(958, NULL, 'positive');
CALL add_medical_history(959, NULL, 'positive');
CALL add_medical_history(960, NULL, 'positive');
CALL add_medical_history(961, NULL, 'positive');
CALL add_medical_history(962, NULL, 'positive');
CALL add_medical_history(963, NULL, 'positive');
CALL add_medical_history(964, NULL, 'positive');
CALL add_medical_history(965, NULL, 'positive');
CALL add_medical_history(966, NULL, 'positive');
CALL add_medical_history(967, NULL, 'positive');
CALL add_medical_history(968, NULL, 'positive');
CALL add_medical_history(969, NULL, 'positive');
CALL add_medical_history(970, NULL, 'positive');
CALL add_medical_history(971, NULL, 'positive');
CALL add_medical_history(972, NULL, 'positive');
CALL add_medical_history(973, NULL, 'positive');
CALL add_medical_history(974, NULL, 'positive');
CALL add_medical_history(975, NULL, 'positive');
CALL add_medical_history(976, NULL, 'positive');
CALL add_medical_history(977, NULL, 'positive');
CALL add_medical_history(978, NULL, 'positive');
CALL add_medical_history(979, NULL, 'positive');
CALL add_medical_history(980, NULL, 'positive');
CALL add_medical_history(981, NULL, 'positive');
CALL add_medical_history(982, NULL, 'positive');
CALL add_medical_history(983, NULL, 'positive');
CALL add_medical_history(984, NULL, 'positive');
CALL add_medical_history(985, NULL, 'positive');
CALL add_medical_history(986, NULL, 'positive');
CALL add_medical_history(987, NULL, 'positive');
CALL add_medical_history(988, NULL, 'positive');
CALL add_medical_history(989, NULL, 'positive');
CALL add_medical_history(990, NULL, 'positive');
CALL add_medical_history(991, NULL, 'positive');
CALL add_medical_history(992, NULL, 'positive');
CALL add_medical_history(993, NULL, 'positive');
CALL add_medical_history(994, NULL, 'positive');
CALL add_medical_history(995, NULL, 'positive');
CALL add_medical_history(996, NULL, 'positive');
CALL add_medical_history(997, NULL, 'positive');
CALL add_medical_history(998, NULL, 'negative');
CALL add_medical_history(999, NULL, 'negative');
CALL add_medical_history(1000, NULL, 'negative');
